.travis.yml

**Affects:** sonar-codequality-collector v3.1.0.
---

Add hygieia team contact information

---

pom.xml

**Affects:** \sonar-collector-v3.1.1-SNAPSHOT
---

increment version to 3.1.1-SNAPSHOT

---

pom.xml
src/main/java/com/capitalone/dashboard/collector/DefaultSonar56Client.java
src/main/java/com/capitalone/dashboard/collector/DefaultSonar6Client.java
src/main/java/com/capitalone/dashboard/collector/DefaultSonarClient.java
src/test/java/com/capitalone/dashboard/collector/DefaultSonar6ClientTest.java

Refactor: use common RestClient to make rest calls, so that error handling and log lines can be standardized

Refactor: use common RestClient to make rest calls

---

src/main/java/com/capitalone/dashboard/collector/DefaultSonar6Client.java
src/main/java/com/capitalone/dashboard/collector/DefaultSonarClient.java

Sonar collector restInfo

---

src/main/java/com/capitalone/dashboard/collector/SonarCollectorTask.java

Added token

---

pom.xml

increment version to 3.1.3-SNAPSHOT

---

src/main/java/com/capitalone/dashboard/collector/SonarCollectorTask.java
src/main/java/com/capitalone/dashboard/model/SonarProject.java

Sonar collector - update all projects matching project name and isntanceUrl

---

src/main/java/com/capitalone/dashboard/collector/SonarCollectorTask.java

Delete unwanted collector-items (CodeQuality)

---

docker/properties-builder.sh

The key names in properties-builder.sh don't match with releavant keys in the pojo (SonarSettings.java). Hence in the container, auth fails as usernames and passwords aren't set and api calls return 401.
Refer: com.capitalone.dashboard.collector.SonarSettings.java
---

Fix bug where value for auth keys aren't picked

---

src/main/java/com/capitalone/dashboard/collector/SonarCollectorTask.java

removed deleteUnwantedJobs()
---

removed deleteUnwantedJobs()

---

pom.xml

updated version to 3.1.4-SNAPSHOT

---

pom.xml

updated version to 3.1.5-SNAPSHOT

---

pom.xml
src/main/java/com/capitalone/dashboard/Application.java
src/main/java/com/capitalone/dashboard/controller/PingController.java

Ping Sonar collector

---

src/main/java/com/capitalone/dashboard/collector/DefaultSonar6Client.java
src/main/java/com/capitalone/dashboard/collector/DefaultSonar8Client.java
src/test/java/com/capitalone/dashboard/collector/DefaultSonar6ClientTest.java
src/test/java/com/capitalone/dashboard/collector/DefaultSonar8ClientTest.java
src/test/resources/com/capitalone/dashboard/collector/sonar8analyses.json
src/test/resources/com/capitalone/dashboard/collector/sonar8measures.json
src/test/resources/com/capitalone/dashboard/collector/sonar8projects.json

**Affects:** \3.1.6 (and earlier)
---
Continuing the support of Sonar 8.3, the `/api/measures` requires a `component` param  (changed from `componentId` https://next.sonarqube.com/sonarqube/web_api/api/measures
Refactored a bit to make the changes easier and added tests for it.

Sonar 8.3 measures changes

---

src/main/java/com/capitalone/dashboard/collector/DefaultSonar6Client.java
src/main/java/com/capitalone/dashboard/collector/SonarClient.java
src/main/java/com/capitalone/dashboard/collector/SonarCollectorTask.java

This PR will detect 404 errors from component Ids no longer being valid.  Later on, when the 404 exception is detected, it will set the project to false so in the future, it will not be triggered (code looks at all enabled projects)

Fix excessive number of Sonar exceptions from 404

---

src/main/java/com/capitalone/dashboard/collector/SonarCollectorTask.java

Add log lines when meta data is modified

Add log lines

---

pom.xml

update mongodb 3.6.x to support AWS DocumentDB

---

pom.xml

Update pom snapshot for sonar changes

---

pom.xml
src/main/java/com/capitalone/dashboard/collector/DefaultSonar6Client.java

allow blank passwords

---

pom.xml
src/main/java/com/capitalone/dashboard/collector/SonarCollectorTask.java

Sonar projectId null check

---

pom.xml
src/main/java/com/capitalone/dashboard/collector/DefaultSonar6Client.java
src/main/java/com/capitalone/dashboard/collector/DefaultSonarClient.java
src/main/java/com/capitalone/dashboard/collector/SonarClient.java
src/main/java/com/capitalone/dashboard/collector/SonarCollectorTask.java
src/main/java/com/capitalone/dashboard/controller/SonarController.java
src/main/java/com/capitalone/dashboard/repository/SonarProjectRepository.java
src/main/java/com/capitalone/dashboard/util/SonarCollectorUtil.java

sonar refresh data by individual project

sonar refresh data by individual project

---

pom.xml

sonar collector version update

sonar collector version update

---

pom.xml

Update core version for log enhancement

---

pom.xml
src/main/java/com/capitalone/dashboard/collector/SonarCollectorTask.java

Core version update and log enhancement
